# Generated by Django 5.0.4 on 2025-04-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
