# Generated by Django 5.0.4 on 2025-05-07 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0003_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="datetime_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="datetime_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
