# Generated by Django 5.0.4 on 2025-06-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0006_comment_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="state",
            field=models.CharField(
                choices=[("a", "تایید شده"), ("r", "رد شده"), ("p", "در انتظار تایید")],
                default="p",
                max_length=1,
                verbose_name="وضعیت کامنت",
            ),
        ),
    ]
