# Generated by Django 5.0.4 on 2025-06-12 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0007_alter_comment_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blogpost.blogpost",
                verbose_name="پست",
            ),
        ),
    ]
