# Generated by Django 5.0.4 on 2025-06-19 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0008_alter_comment_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpost",
            name="likes",
        ),
    ]
