# Generated by Django 5.0.4 on 2025-06-19 12:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0010_blogpostlikes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="blogpostlikes",
            unique_together={("post", "user")},
        ),
    ]
