# Generated by Django 5.0.4 on 2025-06-19 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0012_blogpost_likes_alter_blogpost_author_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="blogpost_likes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
