# Generated by Django 5.0.4 on 2025-06-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogpost", "0013_alter_blogpost_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="pictures/"),
        ),
    ]
