# Generated by Django 5.0.4 on 2025-04-23 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(null=True)),
                ("price_toman", models.IntegerField()),
                ("price_takhfif", models.DecimalField(decimal_places=1, max_digits=4)),
                ("is_ready", models.BooleanField(default=True)),
                ("date_created", models.DateField()),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_modified", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("site_address", models.URLField(null=True)),
                ("test12", models.SlugField(null=True)),
                ("test13", models.ImageField(null=True, upload_to="")),
                ("test14", models.FileField(null=True, upload_to="")),
                ("test15", models.GenericIPAddressField(null=True)),
                ("test16", models.UUIDField(null=True)),
                ("test17", models.JSONField(null=True)),
                (
                    "test18",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
