# Generated by Django 5.0.4 on 2025-04-23 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tamrin", "0003_alter_car_description_alter_car_price_toman"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="price_toman",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
