# Generated by Django 5.0.4 on 2025-04-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tamrin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="site_address",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="test12",
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="test13",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="car",
            name="test14",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="car",
            name="test15",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="test16",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="car",
            name="test17",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
