# Generated by Django 5.0.4 on 2025-04-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=63)),
                ("color", models.CharField(max_length=63)),
                ("model", models.CharField(max_length=63)),
                ("date", models.DateField()),
                ("price", models.PositiveIntegerField()),
                ("country", models.CharField(max_length=63)),
                ("accelerate", models.DecimalField(decimal_places=3, max_digits=4)),
                (
                    "gear_type",
                    models.CharField(
                        choices=[("automat", "اتوماتیک"), ("manual", "دستی")],
                        max_length=63,
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_modified", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
