# Generated by Django 5.1.2 on 2025-07-23 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=11,
                        validators=[
                            django.core.validators.MinLengthValidator(
                                11, "کمتر از ۱۱ رقم وارد نکنید."
                            ),
                            django.core.validators.MaxLengthValidator(
                                11, "بیشتر از ۱۱ رقم وارد نکنید."
                            ),
                        ],
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, "سفارش باید بیش از ۱ عدد باشد."
                            ),
                            django.core.validators.MaxValueValidator(
                                10, "سفارش باید کمتر از ۱۱ عدد باشد."
                            ),
                        ]
                    ),
                ),
            ],
        ),
    ]
