# Generated by Django 5.1.2 on 2025-08-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "surname",
                    models.CharField(max_length=255, verbose_name="نام خانوادگی"),
                ),
                ("age", models.PositiveIntegerField(verbose_name="Age")),
            ],
        ),
    ]
