# Generated by Django 5.1.2 on 2025-08-20 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alaki", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="age2",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Age2"
            ),
        ),
    ]
